#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor HDMI-2 -d I II
# bspc monitor eDP-1 -d III IV

bspc monitor -d I II III IV
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#ffaaff

bspc rule -a telegram-desktop desktop='^2'
bspc rule -a Brave-browser desktop='^2' focus=on
bspc rule -a Alacritty desktop='^1' focus=on

if ! pgrep "polybar" > /dev/null 2>&1 ; then
    ~/.config/polybar/launch.sh &
fi

picom --config $HOME/.config/bspwm/picom.conf &
