#!/usr/bin/env bash
# Generate fuzzel's [colors] section from the active theme's roles. fuzzel.ini
# includes the output; fuzzel reads it on every launch, so there is no reload.
set -euo pipefail

THEME_HOME="${THEME_HOME:-$HOME/.config/theme}"
RESOLVE="$THEME_HOME/lib/resolve.sh"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/theme"
OUT="$STATE_DIR/fuzzel-colors.ini"
mkdir -p "$STATE_DIR"

# fuzzel colors are rrggbbaa with no '#'.
c() { local h; h="$(bash "$RESOLVE" role "$1")"; echo "${h#\#}${2:-ff}"; }

cat > "$OUT" <<INI
# Generated by ~/.config/theme — do not edit; regenerated on theme switch.
[colors]
background=$(c bg)
text=$(c fg)
prompt=$(c accent)
placeholder=$(c muted)
input=$(c fg)
match=$(c accent)
selection=$(c surface)
selection-text=$(c fg)
selection-match=$(c accent2)
border=$(c accent)
INI
