#!/usr/bin/env bash
# Generate a lazygit theme (gui.theme block) from the active theme's roles.
# env.sh points LG_CONFIG_FILE at the output.
set -euo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

THEME_HOME="${THEME_HOME:-$HOME/.config/theme}"
RESOLVE="$THEME_HOME/lib/resolve.sh"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/theme"
OUT="$STATE_DIR/lazygit.yml"
mkdir -p "$STATE_DIR"

r() { bash "$RESOLVE" role "$1"; }

cat > "$OUT" <<YAML
# Generated by ~/.config/theme — do not edit; regenerated on theme switch.
gui:
  theme:
    activeBorderColor:
      - "$(r accent)"
      - bold
    inactiveBorderColor:
      - "$(r muted)"
    optionsTextColor:
      - "$(r accent2)"
    selectedLineBgColor:
      - "$(r surface)"
    selectedRangeBgColor:
      - "$(r surface)"
    cherryPickedCommitBgColor:
      - "$(r surface)"
    cherryPickedCommitFgColor:
      - "$(r accent)"
    unstagedChangesColor:
      - "$(r urgent)"
    defaultFgColor:
      - "$(r fg)"
YAML
