#!/usr/bin/env bash
# Generate waybar color definitions from the active theme's roles. waybar's
# style.css imports the output and styles with @bg, @accent, …; `theme reapply`
# sends SIGUSR2 so a running bar reloads it.
set -euo pipefail

THEME_HOME="${THEME_HOME:-$HOME/.config/theme}"
RESOLVE="$THEME_HOME/lib/resolve.sh"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/theme"
OUT="$STATE_DIR/waybar-colors.css"
mkdir -p "$STATE_DIR"

{
  echo "/* Generated by ~/.config/theme — do not edit; regenerated on theme switch. */"
  for role in bg surface fg muted accent accent2 ok warn urgent info; do
    echo "@define-color $role $(bash "$RESOLVE" role "$role");"
  done
  # Readable text on the accent, for the inverted focused workspace.
  echo "@define-color on_accent $(bash "$RESOLVE" role-on accent);"
} > "$OUT"
