#!/usr/bin/env bash
# Generate Hyprland window-border colors from the active theme's roles: an
# accent → accent2 gradient on the focused window, muted on the rest (the same
# pairing theme-borders gives JankyBorders on macOS). hyprland.lua loads the
# output with dofile; `theme reapply` runs `hyprctl reload` afterwards.
set -euo pipefail

THEME_HOME="${THEME_HOME:-$HOME/.config/theme}"
RESOLVE="$THEME_HOME/lib/resolve.sh"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/theme"
OUT="$STATE_DIR/hyprland.lua"
mkdir -p "$STATE_DIR"

# Hyprland colors are rgba(rrggbbaa) with no '#'.
rgba() { local h; h="$(bash "$RESOLVE" role "$1")"; echo "rgba(${h#\#}$2)"; }

cat > "$OUT" <<LUA
-- Generated by ~/.config/theme — do not edit; regenerated on theme switch.
hl.config({
    general = {
        col = {
            active_border   = { colors = { "$(rgba accent ff)", "$(rgba accent2 ff)" }, angle = 45 },
            inactive_border = "$(rgba muted aa)",
        },
    },
})
LUA
