#!/usr/bin/env bash
# Generate swaync's color variables from the active theme's roles. swaync's
# style.css imports the stock stylesheet and then this file, so only the colors
# change; `theme reapply` runs `swaync-client --reload-css`.
set -euo pipefail

THEME_HOME="${THEME_HOME:-$HOME/.config/theme}"
RESOLVE="$THEME_HOME/lib/resolve.sh"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/theme"
OUT="$STATE_DIR/swaync.css"
mkdir -p "$STATE_DIR"

r() { bash "$RESOLVE" role "$1"; }
# "r, g, b" triplet, the form swaync's --noti-bg variable expects.
triplet() { local h; h="$(r "$1")"; printf '%d, %d, %d' "0x${h:1:2}" "0x${h:3:2}" "0x${h:5:2}"; }

cat > "$OUT" <<CSS
/* Generated by ~/.config/theme — do not edit; regenerated on theme switch. */
:root {
  --cc-bg: $(r bg);
  --noti-border-color: $(r muted);
  --noti-bg: $(triplet bg);
  --noti-bg-alpha: 0.95;
  --noti-bg-darker: $(r surface);
  --noti-bg-hover: $(r surface);
  --noti-bg-focus: $(r surface);
  --noti-close-bg: $(r surface);
  --noti-close-bg-hover: $(r muted);
  --text-color: $(r fg);
  --text-color-disabled: $(r muted);
  --bg-selected: $(r accent);
}
CSS
