#!/usr/bin/env bash
# Generate the browser userstyles from the active theme's roles.
#
# Every readers/web/<domain>.css is a hand-written style that paints one site
# using --theme-* variables. This script resolves those variables for the active
# theme and writes ~/.local/state/theme/<domain>.user.css.
#
# Install each generated file ONCE in Stylus: open its file:// URL in the
# browser and tick "Live reload" (Stylus needs "Allow access to file URLs").
# After that, every `theme reapply` repaints the site without touching Stylus.
set -euo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

THEME_HOME="${THEME_HOME:-$HOME/.config/theme}"
RESOLVE="$THEME_HOME/lib/resolve.sh"
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/web"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/theme"
ROLES="bg surface fg muted accent accent2 ok warn urgent info"

mkdir -p "$STATE_DIR"
[ -d "$SRC_DIR" ] || exit 0

theme="$(bash "$RESOLVE" current-name)"
polarity="$(bash "$RESOLVE" polarity)"

# Each role as both #rrggbb and an "r, g, b" triplet, so a style can build
# translucent shades with rgba(var(--theme-fg-rgb), .1).
role_vars() {
  local role hex
  for role in $ROLES; do
    hex="$(bash "$RESOLVE" role "$role")"
    printf '    --theme-%s: %s;\n' "$role" "$hex"
    printf '    --theme-%s-rgb: %d, %d, %d;\n' "$role" \
      "0x${hex:1:2}" "0x${hex:3:2}" "0x${hex:5:2}"
  done
}

for src in "$SRC_DIR"/*.css; do
  [ -e "$src" ] || continue
  domain="$(basename "$src" .css)"
  out="$STATE_DIR/$domain.user.css"
  tmp="$STATE_DIR/.$domain.user.css.tmp"
  {
    cat <<HEADER
/* ==UserStyle==
@name           ${domain} — terminal
@namespace      ivan.theme
@version        1.0.0
@description    ${domain} restyled to match the active terminal theme.
@author         Ivan
==/UserStyle== */

/* Generated by ~/.config/theme (${theme}, ${polarity}) — do not edit.
   Source: ~/.config/theme/readers/web/${domain}.css */

@-moz-document domain("${domain}") {
  :root {
HEADER
    role_vars
    echo "  }"
    echo
    cat "$src"
    echo "}"
  } > "$tmp"
  mv -f "$tmp" "$out"
  echo "gen-web-usercss: $out"
done
